-- Neo-tree is a Neovim plugin to browse the file system
-- https://github.com/nvim-neo-tree/neo-tree.nvim
return {
  -- 'nvim-neo-tree/neo-tree.nvim',
  -- dependencies = {
  --   'nvim-lua/plenary.nvim',
  --   'nvim-tree/nvim-web-devicons', -- not strictly required, but recommended
  --   'MunifTanjim/nui.nvim',
  -- },
  -- cmd = 'Neotree',
  -- keys = {
  --   { '\\', ':Neotree toggle<CR>', { desc = 'NeoTree reveal' } },
  --   { '<leader>b', '<cmd>Neotree toggle<CR>', desc = 'Open Neotree' },
  --   { '<C-b>', '<cmd>Neotree toggle<CR>', desc = 'Open Neotree' },
  -- },
  -- opts = {
  --   window = {
  --     position = 'float',
  --   },
  --   filesystem = {
  --     window = {
  --       mappings = {
  --         ['\\'] = 'close_window',
  --         ['<c-b>'] = 'close_window',
  --       },
  --     },
  --   },
  -- },

  -- 'nvim-telescope/telescope-file-browser.nvim',
  -- dependencies = { 'nvim-telescope/telescope.nvim', 'nvim-lua/plenary.nvim' },
  -- require('telescope').setup {
  -- extensions = {
  --   file_browser = {
  --     theme = 'ivy',
  --     -- disables netrw and use telescope-file-browser in its place
  --     hijack_netrw = true,
  --     mappings = {
  --       ['i'] = {
  --         -- your custom insert mode mappings
  --       },
  --       ['n'] = {
  --         -- your custom normal mode mappings
  --       },
  --     },
  --   },
  -- },
  -- },
  -- To get telescope-file-browser loaded and working with telescope,
  -- you need to call load_extension, somewhere after setup function:
  -- require('telescope').load_extension 'file_browser',
}
